version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  celery:
    build:
      context: .
      dockerfile: worker.Dockerfile
    volumes:
      - .:/app
    ports:
      - "5678:5678"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"



# services:
#   taskq:
#     image: taskq
#     build:
#       context: .
#       dockerfile: app.dockerfile
#     ports:
#       - 8000:8000

#   redis:
#     image: redis:alpine
#     restart: always
#     ports:
#       - "6380:6379"

#   celery:
#     build:
#       context: .
#       dockerfile: celery_worker.dockerfile
#     restart: always
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - CELERY_BROKER_URL="redis://redis:6379/0"
#       - CELERY_RESULT_BACKEND="redis://redis:6379/0"
#     volumes:
#       - ./app:/app
#     ports:
#       - "5682:5679"
#     depends_on:
#       - redis

#   flower:
#     image: mher/flower:1.2
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0
#     restart: always
#     ports:
#       - 5555:5555
#     depends_on:
#       - celery
#       - redis
